{{- if .Values.httproute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-httproute
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hesselinkme.labels" . | nindent 4 }}
spec:
  hostnames:
    {{- range .Values.httproute.hostnames }}
    - {{ . | quote }}
    {{- end }}
  parentRefs:
    - name: {{ .Values.httproute.gateway.name }}
      namespace: {{ .Values.httproute.gateway.namespace }}
  rules:
    - matches:
        - path:
            type: {{ .Values.httproute.path.type }}
            value: {{ .Values.httproute.path.value }}
      backendRefs:
        - name: {{ .Release.Name | default (include "hesselinkme.fullname" .) }}
          port: {{ .Values.service.port | default 8080 }}
{{- end }}
