apiVersion: v1
entries:
  anna-nginx:
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:31.03397+01:00"
    description: Anna Nginx Helm chart
    digest: a94b3e8762b2285d7dad2857bd5505a649601fd1d1f400cfa227fab73a8a7f89
    home: https://github.com/shesselink81/static-sites
    icon: https://raw.githubusercontent.com/docker-library/docs/01c12653951b2fe592c1f93a13b4e289ada0e3a1/nginx/logo.png
    maintainers:
    - name: shesselink81
    name: anna-nginx
    sources:
    - https://github.com/shesselink81/static-sites/tree/main/charts/anna-nginx
    type: application
    urls:
    - anna-nginx-0.2.5.tgz
    version: 0.2.5
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:31.0326916+01:00"
    description: Anna Nginx Helm chart
    digest: 5f642500dd415fb6f62ce1b1f34df7a8ec04f483461d0a287e848cbcbc5022e1
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:31.0088927+01:00"
    description: Anna Nginx Helm chart
    digest: cd73d0fcced3d453f834dfff28033f404b1371c36ba7bc54e4c00fb6547cb24d
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:30.9883344+01:00"
    description: Anna Nginx Helm chart
    digest: aaf408c9d52d7459a842452c86f69eecd7a72f65a92e6dd0b6b42ce466949d90
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:30.969194+01:00"
    description: Anna Nginx Helm chart
    digest: 3caf5cc8f0b729e89f0e37ce9f70e7ef2fd40aee7860a5f4e3368c8b58f0ba64
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:30.9504769+01:00"
    description: Anna Nginx Helm chart
    digest: 3a6eb202cb3058fe1231c7f0c94d68d3a116bd9c38a9dbe10b8f9575a0af15c9
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:30.9289023+01:00"
    description: Anna Nginx Helm chart
    digest: a6229df659d56f492c93e6bf6b60c7108ef27fb3eb094579a1660849c1cb5c47
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:30.9095556+01:00"
    description: Anna Nginx Helm chart
    digest: b9ede2ae5189629c32b7af6a254a230febea49f22399dd8021ae5d8bfc94d834
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.1.0.tgz
    version: 0.1.0
  hesselinkme-nginx:
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:31.1782016+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: 6d3e11aa3049496365aeb20276dab94439c4208ac64d4cff23043a719d26f498
    home: https://github.com/shesselink81/static-sites
    icon: https://raw.githubusercontent.com/docker-library/docs/01c12653951b2fe592c1f93a13b4e289ada0e3a1/nginx/logo.png
    maintainers:
    - name: shesselink81
    name: hesselinkme-nginx
    sources:
    - https://github.com/shesselink81/static-sites/tree/main/charts/hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.2.5.tgz
    version: 0.2.5
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:31.1775407+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: 00627cb5a1c943ea238234c17edefe128b77551a6cc7bf674126a94159875218
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:31.1504676+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: 2f7a2cfb09f300b8beeb20dd7242e959006167460fc792f57699fc447d7119f6
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:31.1325435+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: 269fc84eafcbc758da884e514bd3c8ec1b3dd1718fbd8225c0c381a4e67bca2d
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:31.1141845+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: a0e106d72731013b0f5e603d8cb0aac609a166868dc9f6fe7f4c38df0c44bd67
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:31.095299+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: e741737076e65d8d57d607929db8695cd22dd1fca158115b9a52f61027f4f3ff
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:31.0754803+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: df7d9c4c1bed5e4158b0132f694654db97ae92867f68fc3fb4a9e17c949a698d
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T20:25:31.0552821+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: 95271eab36b9ae185b7819c1713d608f012f6818d8c40fdd4bff2f95148a94a1
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-17T20:25:30.8815582+01:00"
