apiVersion: v1
entries:
  anna-nginx:
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T04:25:21.497653+01:00"
    description: Anna Nginx Helm chart
    digest: 3a6eb202cb3058fe1231c7f0c94d68d3a116bd9c38a9dbe10b8f9575a0af15c9
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T04:25:21.4955579+01:00"
    description: Anna Nginx Helm chart
    digest: a6229df659d56f492c93e6bf6b60c7108ef27fb3eb094579a1660849c1cb5c47
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T04:25:21.4758449+01:00"
    description: Anna Nginx Helm chart
    digest: b9ede2ae5189629c32b7af6a254a230febea49f22399dd8021ae5d8bfc94d834
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.1.0.tgz
    version: 0.1.0
  hesselinkme-nginx:
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T04:25:21.5327278+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: df7d9c4c1bed5e4158b0132f694654db97ae92867f68fc3fb4a9e17c949a698d
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T04:25:21.5143088+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: 95271eab36b9ae185b7819c1713d608f012f6818d8c40fdd4bff2f95148a94a1
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-17T04:25:21.4534992+01:00"
