apiVersion: v1
entries:
  anna-nginx:
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.477705+01:00"
    description: Anna Nginx Helm chart
    digest: 5f642500dd415fb6f62ce1b1f34df7a8ec04f483461d0a287e848cbcbc5022e1
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.4771776+01:00"
    description: Anna Nginx Helm chart
    digest: cd73d0fcced3d453f834dfff28033f404b1371c36ba7bc54e4c00fb6547cb24d
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.4589849+01:00"
    description: Anna Nginx Helm chart
    digest: aaf408c9d52d7459a842452c86f69eecd7a72f65a92e6dd0b6b42ce466949d90
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.4389683+01:00"
    description: Anna Nginx Helm chart
    digest: 3caf5cc8f0b729e89f0e37ce9f70e7ef2fd40aee7860a5f4e3368c8b58f0ba64
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.4148078+01:00"
    description: Anna Nginx Helm chart
    digest: 3a6eb202cb3058fe1231c7f0c94d68d3a116bd9c38a9dbe10b8f9575a0af15c9
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.3943683+01:00"
    description: Anna Nginx Helm chart
    digest: a6229df659d56f492c93e6bf6b60c7108ef27fb3eb094579a1660849c1cb5c47
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.3680047+01:00"
    description: Anna Nginx Helm chart
    digest: b9ede2ae5189629c32b7af6a254a230febea49f22399dd8021ae5d8bfc94d834
    name: anna-nginx
    type: application
    urls:
    - anna-nginx-0.1.0.tgz
    version: 0.1.0
  hesselinkme-nginx:
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.6021358+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: 00627cb5a1c943ea238234c17edefe128b77551a6cc7bf674126a94159875218
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.6000261+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: 2f7a2cfb09f300b8beeb20dd7242e959006167460fc792f57699fc447d7119f6
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.5812018+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: 269fc84eafcbc758da884e514bd3c8ec1b3dd1718fbd8225c0c381a4e67bca2d
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.557564+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: a0e106d72731013b0f5e603d8cb0aac609a166868dc9f6fe7f4c38df0c44bd67
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.5330419+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: e741737076e65d8d57d607929db8695cd22dd1fca158115b9a52f61027f4f3ff
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.2.0.tgz
    version: 0.2.0
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.5134363+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: df7d9c4c1bed5e4158b0132f694654db97ae92867f68fc3fb4a9e17c949a698d
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.1.1.tgz
    version: 0.1.1
  - apiVersion: v2
    appVersion: v2.0.3
    created: "2026-01-17T08:43:26.4955462+01:00"
    description: Hesselink.me Nginx Helm chart
    digest: 95271eab36b9ae185b7819c1713d608f012f6818d8c40fdd4bff2f95148a94a1
    name: hesselinkme-nginx
    type: application
    urls:
    - hesselinkme-nginx-0.1.0.tgz
    version: 0.1.0
generated: "2026-01-17T08:43:26.3456099+01:00"
