image:
  repository: quay.io/shesselink81/anna-nginx
  tag: v2.0.9
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 8080

containerPort: 8080

httproute:
  enabled: false
  hostnames:
    - example.com
  gateway:
    name: default-gateway
    namespace: default
  path:
    type: PathPrefix
    value: /
